import subprocess
import random
# subprocess.call(["./myBash.sh","RETURN_COEFF=0.8 IGNORE_COEFF=0.05 EXPLORE_AGAIN=0.25 LOCAL_RANDOM_TO_DESTINATION=0.7 MAX_SHIP_SEED=0.4 MAX_DROP_OFF_SEED=0.035 MAX_ENERGY_POINTS=15 DISTANCE_TO_BUILD_DROPOFF=8 BIGFISH_AMOUNT=400 FIRST_BUILD_SHIP=100 SECOND_MONEY_FOR_PORT=120 THIRD_BUILD_PORT=180 FOUTRH_STOP_BUILD_PORT=320", \
				# "RETURN_COEFF=0.8 IGNORE_COEFF=0.05 EXPLORE_AGAIN=0.25 LOCAL_RANDOM_TO_DESTINATION=0.7 MAX_SHIP_SEED=0.4 MAX_DROP_OFF_SEED=0.035 MAX_ENERGY_POINTS=15 DISTANCE_TO_BUILD_DROPOFF=8 BIGFISH_AMOUNT=400 FIRST_BUILD_SHIP=100 SECOND_MONEY_FOR_PORT=120 THIRD_BUILD_PORT=180 FOUTRH_STOP_BUILD_PORT=320"])

def generateString():
	RETURN_COEFF = random.uniform(0.6,0.95)
	IGNORE_COEFF = random.uniform(0.05,0.3)
	EXPLORE_AGAIN = random.uniform(0.2,0.5)
	LOCAL_RANDOM_TO_DESTINATION = random.uniform(0.3,0.6)
	MAX_SHIP_SEED= random.uniform(0.4,0.7)
	MAX_DROP_OFF_SEED = random.uniform(0.03,0.07)
	MAX_ENERGY_POINTS = random.randint(3,20)
	DISTANCE_TO_BUILD_DROPOFF = random.randint(4,20)
	BIGFISH_AMOUNT=random.randint(200,800)
	FIRST_BUILD_SHIP=random.randint(80,130) 
	SECOND_MONEY_FOR_PORT=random.randint(130,180)
	THIRD_BUILD_PORT=random.randint(180,280)
	FOUTRH_STOP_BUILD_PORT=random.randint(280,350)

	mystring = \
			"RETURN_COEFF="+str(RETURN_COEFF)+\
			" IGNORE_COEFF="+str(IGNORE_COEFF)+\
			" EXPLORE_AGAIN="+str(EXPLORE_AGAIN)+\
			" LOCAL_RANDOM_TO_DESTINATION="+str(LOCAL_RANDOM_TO_DESTINATION)+\
			" MAX_SHIP_SEED="+str(MAX_SHIP_SEED)+\
			" MAX_DROP_OFF_SEED="+str(MAX_DROP_OFF_SEED)+\
			" MAX_ENERGY_POINTS="+str(MAX_ENERGY_POINTS)+\
			" DISTANCE_TO_BUILD_DROPOFF="+str(DISTANCE_TO_BUILD_DROPOFF)+\
			" BIGFISH_AMOUNT="+str(BIGFISH_AMOUNT)+\
			" FIRST_BUILD_SHIP="+str(FIRST_BUILD_SHIP)+\
			" SECOND_MONEY_FOR_PORT="+str(SECOND_MONEY_FOR_PORT)+\
			" THIRD_BUILD_PORT="+str(THIRD_BUILD_PORT)+\
			" FOUTRH_STOP_BUILD_PORT="+str(FOUTRH_STOP_BUILD_PORT)
	myDict = \
			{"RETURN_COEFF": RETURN_COEFF, "IGNORE_COEFF":IGNORE_COEFF, "EXPLORE_AGAIN":EXPLORE_AGAIN,\
			 "LOCAL_RANDOM_TO_DESTINATION":LOCAL_RANDOM_TO_DESTINATION, "MAX_SHIP_SEED":MAX_SHIP_SEED,\
			 "MAX_DROP_OFF_SEED":MAX_DROP_OFF_SEED,"MAX_ENERGY_POINTS":MAX_ENERGY_POINTS,\
			 "DISTANCE_TO_BUILD_DROPOFF":DISTANCE_TO_BUILD_DROPOFF,"BIGFISH_AMOUNT":BIGFISH_AMOUNT,\
			 "FIRST_BUILD_SHIP":FIRST_BUILD_SHIP,"SECOND_MONEY_FOR_PORT":SECOND_MONEY_FOR_PORT,\
			 "THIRD_BUILD_PORT":THIRD_BUILD_PORT,"FOUTRH_STOP_BUILD_PORT":FOUTRH_STOP_BUILD_PORT}

	return mystring,myDict

subprocess.call(["./myBash.sh",generateString()[0], generateString()[0]])
